# Environment:

env:
  conf_path: sumo_env_files/sumo_circuler_net/circle_env.sumocfg
  sensor_range: 80

# Dataset collection configuration
dataset:
  env_conf_path: ./sumo_env_files/sumo_circuler_net/circle_env_data_collection.sumocfg
  folder: ./dataset
  num_episodes: 4000
  num_vehicles: 50


# Train configuration
train:
  dataset_path: dataset/dataset_epi_3000_num_vehicles50_sensor_range_80.npy
  weight_folder: ./weights
  gamma: 0.99
  lr: 0.0001
  tau: 0.0001
  batch_size: 1500
  n_optimization: 1500
  # resume_from: ./weights/agent_and_target_loss_0.17_epochs_1000.pt
  resume_from: None
  model_saving_frequency: 100

# Running configuration
run:
  weight_file: weights/run_id_1681511105/step_1600_loss_0.1017.pt
  # env_conf_path: ./sumo_env_files/sumo_circuler_net/circle_env.sumocfg
  env_conf_path: ./sumo_env_files/sumo_circuler_net/circle_env_data_collection.sumocfg
  num_vehicles: 50

# evaluation 

eval:
  runs_per_agent: 20
  result_folder: ./results
  weights_folder: ./weights/run_id_1681511105
  num_vehicles: 50
  env_conf_path: ./sumo_env_files/sumo_circuler_net/circle_env_data_collection.sumocfg



