# Environment:

env:
  conf_path: sumo_env_files/sumo_circuler_net/circle_env.sumocfg
  sensor_range: 80

# Dataset collection configuration
dataset:
  env_conf_path: ./sumo_env_files/sumo_circuler_net/circle_env_data_collection.sumocfg
  folder: ./dataset
  num_episodes: 2
  num_vehicles: 50


# Train configuration
train:
  dataset_path: dataset/dataset_2000_epi_d_max_80_num_vehicles_50.npy
  result_folder: ./results
  weight_folder: ./weights
  gamma: 0.99
  lr: 0.0001
  tau: 0.0001
  batch_size: 1000
  epochs: 1000

# Running configuration
run:
  weight_file: ./weights/agent_loss_0.17_epoch_999.pt

# evaluation 

eval:
  runs_per_agent: 10
  result_folder: ./results
  weights_folder: ./weights/run_1
  



